image: python:3.6.4-stretch

tox:
  script:
  - pip install tox
  - tox

pages:
  script:
  - pip install sphinx
  - python setup.py install
  - rm -rf docs/source && sphinx-apidoc -e -f -o docs/source/ quart/
  - cd docs/ && make html && cd ../
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

h2spec:
  script:
  - python setup.py install
  - cd compliance/h2spec && nohup python server.py &
  - wget https://github.com/summerwind/h2spec/releases/download/v2.1.0/h2spec_linux_amd64.tar.gz
  - tar -xvf h2spec_linux_amd64.tar.gz
  - sleep 10
  - ./h2spec -tk -h 127.0.0.1 -p 5000

autobahn:
  image: python:2.7.14-alpine3.7
  script:
  - apk --update add build-base libressl libressl-dev ca-certificates libffi-dev python3
  - pip install autobahntestsuite
  - python3 setup.py install
  - cd compliance/autobahn && nohup python3 server.py &
  - cd compliance/autobahn && wstest -m fuzzingclient && python summarise.py
