py37:
  image: python:3.7
  script:
  - pip install tox
  - tox -e py37

py38:
  image: python:3.8
  script:
  - pip install tox
  - tox -e py38

py39:
  image: python:3.9
  script:
  - pip install tox
  - tox -e docs,format,mypy,py39,pep8,setuppy,manifest

pages:
  image: python:3.9
  script:
  - pip install sphinx pydata-sphinx-theme
  - python setup.py install
  - rm -rf docs/source && sphinx-apidoc -e -f -o docs/reference/source/ src/quart/
  - cd docs/ && make html && cd ../
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
